//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebRH.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agrupaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agrupaciones()
        {
            this.Departamentos = new HashSet<Departamentos>();
        }
    
        public byte Id_Agrup { get; set; }
        public string Nom_Agrup { get; set; }
        public string BaseDatos { get; set; }
        public string Alias { get; set; }
        public string Produce { get; set; }
        public string Id_Scta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departamentos> Departamentos { get; set; }
    }
}
