//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebRH.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LectorHuellasEntities : DbContext
    {
        public LectorHuellasEntities()
            : base("name=LectorHuellasEntities")
        {
    	base.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<PersonalImagen> PersonalImagen { get; set; }
        public virtual DbSet<RegistroES> RegistroES { get; set; }
        public virtual DbSet<RegistroESpejo> RegistroESpejo { get; set; }
    }
}
