//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebRH.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalImagen
    {
        public int ID { get; set; }
        public byte[] Imagen { get; set; }
        public int Solapin { get; set; }
        public string NombreDedo { get; set; }
        public string DirImagen { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
