//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebRH.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecursosHumanosEntities : DbContext
    {
        public RecursosHumanosEntities()
            : base("name=RecursosHumanosEntities")
        {
    	base.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agrupaciones> Agrupaciones { get; set; }
        public virtual DbSet<COcupacional> COcupacional { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<PersonalRH> Personal { get; set; }
        public virtual DbSet<Plantilla> Plantilla { get; set; }
        public virtual DbSet<BajasPers> BajasPers { get; set; }
        public virtual DbSet<GCientifico> GCientifico { get; set; }
        public virtual DbSet<Plazas> Plazas { get; set; }
        public virtual DbSet<BajaPlantilla> BajaPlantilla { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<CBiotecnologicas> CBiotecnologicas { get; set; }
        public virtual DbSet<CCientificas> CCientificas { get; set; }
        public virtual DbSet<CDocente> CDocente { get; set; }
        public virtual DbSet<CTecnologicas> CTecnologicas { get; set; }
    }
}
