//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebRH.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroES
    {
        public int Exp { get; set; }
        public string Fecha { get; set; }
        public string Tipo { get; set; }
        public string IP { get; set; }
    }
}
